'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace Proyecto_Sistema_Bolpa

    Partial Public Class ProyectoBDEntities1
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=ProyectoBDEntities1")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property tblArticulo() As DbSet(Of tblArticulo)
        Public Overridable Property tblCliente() As DbSet(Of tblCliente)
        Public Overridable Property tblDetalleFactura() As DbSet(Of tblDetalleFactura)
        Public Overridable Property tblEmpleado() As DbSet(Of tblEmpleado)
        Public Overridable Property tblFacturaCliente() As DbSet(Of tblFacturaCliente)
        Public Overridable Property tblFacturaNula() As DbSet(Of tblFacturaNula)
        Public Overridable Property tblFacturaProveedor() As DbSet(Of tblFacturaProveedor)
        Public Overridable Property tblInventario() As DbSet(Of tblInventario)
        Public Overridable Property tblProveedor() As DbSet(Of tblProveedor)
        Public Overridable Property tblUsuario() As DbSet(Of tblUsuario)
    
    End Class

End Namespace
