'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Proyecto_Sistema_Bolpa

    Partial Public Class tblFacturaProveedor
        Public Property Codigo As String
        Public Property NumFactura As Integer
        Public Property TipoFactura As String
        Public Property CedulaProveedor As String
        Public Property CedulaEmpleado As String
        Public Property Fecha As Date
        Public Property Hora As System.TimeSpan
        Public Property IdDetalle As Integer
        Public Property Estado As String
    
        Public Overridable Property tblDetalleFactura As tblDetalleFactura
        Public Overridable Property tblEmpleado As tblEmpleado
        Public Overridable Property tblProveedor As tblProveedor
    
    End Class

End Namespace
