'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Proyecto_Sistema_Bolpa

    Partial Public Class tblInventario
        Public Property Id As Integer
        Public Property CedulaProveedor As String
        Public Property IdArticulo As Integer
        Public Property UnidadesExistentes As Integer
        Public Property Monto As Decimal
    
        Public Overridable Property tblArticulo As tblArticulo
        Public Overridable Property tblProveedor As tblProveedor
    
    End Class

End Namespace
