'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Proyecto_Sistema_Bolpa

    Partial Public Class tblProveedor
        Public Property Cedula As String
        Public Property Nombre As String
        Public Property PrimerApe As String
        Public Property SegundoApe As String
        Public Property TipoPersona As String
        Public Property FechaNac As Date
        Public Property Nacionalidad As String
        Public Property Telefono As String
        Public Property Direccion As String
        Public Property Email As String
        Public Property SitioWeb As String
        Public Property FechaIngreso As Date
        Public Property Estado As String
    
        Public Overridable Property tblFacturaProveedor As ICollection(Of tblFacturaProveedor) = New HashSet(Of tblFacturaProveedor)
        Public Overridable Property tblInventario As ICollection(Of tblInventario) = New HashSet(Of tblInventario)
    
    End Class

End Namespace
