'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Proyecto_Sistema_Bolpa

    Partial Public Class tblUsuario
        Public Property id As Integer
        Public Property Cedula As String
        Public Property Nombre As String
        Public Property Contraseña As String
        Public Property TipoUsuario As String
    
        Public Overridable Property tblEmpleado As tblEmpleado
    
    End Class

End Namespace
